apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: NAME01-monitor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: ''
    server: 'https://kubernetes.default.svc' 
  project: default
  source:
    path: gitops/NAME01/monitor/
    repoURL: 'https:/github.com/maxxam123/platform01.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: NAME01-bootstrap
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: ''
    server: 'https://kubernetes.default.svc' 
  project: default
  source:
    path: gitops/NAME01/bootstrap/
    repoURL: 'https:/github.com/maxxam123/platform01.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
