apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: ingress
  namespace: ingress-nginx
spec:
  rules:
    - host: 
      http:
        paths:
          - backend:
              service:
                name: 
                port:
                  number: 80
            path: /
            pathType:
