on:
 push:
   branches:
   - main
   paths:
   #- 'cluster/aws06/provider.tf'
   - 'cluster/aws06/*'
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: bootstrapTerraform
          run: |

            git clone https://github.com/maxxam123/platform01.git

            NAME=$( sed -n 1p cluster/aws06/provider.tf )
            PROVIDER=$( sed -n 2p cluster/aws06/provider.tf )

            mkdir -p platform01/.github/workflows
            mkdir -p platform01/cluster/aws06
            mkdir -p platform01/gitops/aws06/{bootstrap,monitor}

            cp -r cluster/aws06/terraform.tfvars  platform01/cluster/aws06/
            cp -r templates/pipelines/test_create.yaml platform01/.github/workflows/aws06.yaml
            cp -r gitops/aws06/bootstrap/* platform01/gitops/aws06/bootstrap/
            cp -r gitops/aws06/monitor/* platform01/gitops/aws06/monitor/

            sed -i -e "s/NAME/$NAME/g"         platform01/.github/workflows/aws06.yaml
            sed -i -e "s/PROVIDER/$PROVIDER/g" platform01/.github/workflows/aws06.yaml

