on:
 push:
   branches:
   - main
   paths:
   - 'new/delete_cluster/delete.yaml'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: delete cluster
          run: |
          
            NAME=$( sed -n 1p new/delete_cluster/delete.yaml )
            git clone https://github.com/maxxam123/platform01.git
            ls -la
            ls -la platform01
            cp templates/pipelines/delete_pipeline.yaml platform01/.github/workflows/
            sed -i -e "s/NAME/$NAME/g" platform01/.github/workflows/delete_pipeline.yaml
            cd platform01
            mkdir -p delete_cluster
            date > delete_cluster/delete.yaml
            cd ..

        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
          with:
            source-directory: "platform01"
            destination-github-username: "maxxam123"
            destination-repository-name: "platform01"
            user-email: hennighausenmax@gmail.com
            target-branch: main
