on:
 push:
   branches:
   - main
   paths:
   - 'test/delete_cluster.yaml'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: test
          run: |
          
            var=$( sed -n 1p test/DELETE )
            git clone https://github.com/maxxam123/platform01.git
            ls -la
            ls -la platform01
            cp templates/pipelines/delete_pipeline platform01/.github/workflows/delete.yaml
            sed -i -e "s/NAME/$var/g" platform01/.github/workflows/delete.yaml
            cd platform01
            mkdir -p delete
            date > delete/delete.yaml
            cd ..

        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
          with:
            source-directory: "platform01"
            destination-github-username: "maxxam123"
            destination-repository-name: "platform01"
            user-email: hennighausenmax@gmail.com
            target-branch: main
