on:
 push:
   branches:
   - main
   paths:
   - 'new/forever/provider'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: main pipeline
          run: |

            git clone https://github.com/maxxam123/platform03.git

            #path=/home/runner/work/platform03/platform03/cluster
            ls -la
            ls platform03
              
              NAME01=$( sed -n 1p new/_*/provider.tf )
              PROVIDER01=$( sed -n 2p new/_*/provider.tf )
              cp templates/pipelines/local_pipeline.yaml .

              sed -i -e "s/NAME01/$NAME01/g" local_pipeline.yaml      
              sed -i -e "s/PROVIDER01/$PROVIDER01/g" local_pipeline.yaml
              cp local_pipeline.yaml platform03/.github/workflows/$NAME01.yaml
              mkdir -p platform03/cluster/$NAME01
              cp new/_*/provider.tf platform03/cluster/$NAME01/
              cp new/_*/terraform.tfvars platform03/cluster/$NAME01/
      
              ### GITOPS ###

              mkdir -p platform03/gitops/$NAME01
              mkdir -p platform03/gitops/$NAME01/eso
              mkdir -p platform03/gitops/$NAME01/nginx
              REPLICAS=$( sed -n 3p new/_*/provider.tf )
              LOADBALANCER=$( sed -n 4p new/_*/provider.tf )
              SECRET=$( sed -n 5p new/_*/provider.tf )

                ### ESO ###
              cp templates/gitops/eso/* platform03/gitops/$NAME01/eso/
              sed -i -e "s/SECRET/$SECRET/g" platform03/gitops/$NAME01/eso/values.yaml
                ### NGINX ###
              cp templates/gitops/nginx/* platform03/gitops/$NAME01/nginx/
              sed -i -e "s/REPLICAS/$REPLICAS/g" platform03/gitops/$NAME01/nginx/values.yaml
              sed -i -e "s/LOADBALANCER/$LOADBALANCER/g" platform03/gitops/$NAME01/nginx/values.yaml
              
              
              #rm -rf platform03/new/_*

        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
          with:
            source-directory: "platform03"
            destination-github-username: "maxxam123"
            destination-repository-name: "platform03"
            user-email: hennighausenmax@gmail.com
            target-branch: main
