on:
 push:
   branches:
   - main
   paths:
   - 'new/_*/provider.tf'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: main pipeline
          run: |

            git clone https://github.com/maxxam123/platform03.git

            #path=/home/runner/work/platform03/platform03/cluster
            ls -la
            ls platform03
              
              NAME01=$( sed -n 1p new/_*/provider.tf )
              PROVIDER01=$( sed -n 2p new/_*/provider.tf )
              cp templates/pipelines/local_pipeline.yaml .

              sed -i -e "s/NAME01/$NAME01/g" local_pipeline.yaml      
              sed -i -e "s/PROVIDER01/$PROVIDER01/g" local_pipeline.yaml
              cp local_pipeline.yaml platform03/.github/workflows/$NAME01.yaml
              mkdir -p platform03/cluster/$NAME01
              cp new/_*/provider.tf platform03/cluster/$NAME01/
              cp new/_*/terraform.tfvars platform03/cluster/$NAME01/
              #rm -rf new/_*
              
              cat local_pipeline.yaml
              ls -la

        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
          with:
            source-directory: "platform03"
            destination-github-username: "maxxam123"
            destination-repository-name: "platform03"
            user-email: hennighausenmax@gmail.com
            target-branch: main
