on:
 push:
   branches:
   - main
   paths:
   - 'new/test_forever/create'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: main pipeline
          run: |

            git clone https://github.com/maxxam123/platform03.git
            ls -la
              
              NAME01=$( sed -n 1p new/_*/provider.tf )
              PROVIDER01=$( sed -n 2p new/_*/provider.tf )
              cp templates/pipelines/test_local_pipeline.yaml .

              #################
              cp new/_*/application.tf application.tf
              cp new/_*/provider2.tf provider.tf

              cp templates/applications/create_application.yaml .
              sed -i -e "s/NAME01/$NAME01/g" create_application.yaml
              mkdir -p platform03/applications/$NAME01 
              cp create_application.yaml platform03/applications/$NAME01/create_application.yaml

              sed -i -e "s/NAME01/$NAME01/g" test_local_pipeline.yaml      
              sed -i -e "s/PROVIDER01/$PROVIDER01/g" test_local_pipeline.yaml
              cp test_local_pipeline.yaml platform03/.github/workflows/$NAME01.yaml
              mkdir -p platform03/cluster/$NAME01

              mkdir -p platform03/gitops/$NAME01/bootstrap/{eso,velero,certmanager,nginx}
              mkdir -p platform03/gitops/$NAME01/monitor/{prometheus,thanos}

              ####################
              sed -i -e "s/TERRAFORM/$NAME01/g" application.tf
              sed -i -e "s/TERRAFORM/$NAME01/g" provider.tf
              cp application.tf platform03/cluster/$NAME01/application.tf
              cp provider.tf platform03/cluster/$NAME01/provider.tf
              
              cp new/_*/provider.tf platform03/cluster/$NAME01/info.tf
              cp new/_*/terraform.tfvars platform03/cluster/$NAME01/terraform.tfvars

              bootstrap=/home/runner/work/platform03/platform03/templates/gitops/bootstrap
              monitor=/home/runner/work/platform03/platform03/templates/gitops/monitor

              ### BOOTSTRAP ###
              for each in $(ls $bootstrap); do
                cd $bootstrap/$each
                VAR=$(cat /home/runner/work/platform03/platform03/new/_*/provider.tf | grep $each | awk '{print $2}')
                  if [ $VAR ]
                    then cp $bootstrap/$each/* ../../../../platform03/gitops/$NAME01/bootstrap/$each/
                    else echo empty
                  fi
              done

              ### MONITOR ###
              for each in $(ls $monitor); do
                cd $monitor/$each
                VAR=$(cat /home/runner/work/platform03/platform03/new/_*/provider.tf | grep $each | awk '{print $2}')
                  if [ $VAR ]
                    then cp $monitor/$each/* ../../../../platform03/gitops/$NAME01/monitor/$each/
                    else echo empty
                  fi
              done

        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
          with:
            source-directory: "platform03"
            destination-github-username: "maxxam123"
            destination-repository-name: "platform03"
            user-email: hennighausenmax@gmail.com
            target-branch: main
